# Generated by Django 4.2.5 on 2023-11-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('resourceId', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('traceId', models.CharField(max_length=100)),
                ('spanId', models.CharField(max_length=100)),
                ('commit', models.CharField(max_length=100)),
                ('parentResourceId', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
